pipeline {
    agent {
        docker {
            image 'node:12.18.1'
            args '-p 3000:3000'
        }
    }

    stages {
        stage('Build') {
            steps {
                echo 'Installing'
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing'
                sh 'npm run test'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying'
                def customImage = docker.build("my-image:${env.BUILD_ID}")
                customImage.inside {
                    sh 'npm start'
                }
            }
        }
    }
}
